language: java
jdk:
  - openjdk8
  - openjdk11

notifications:
  email:
    - github@graphhopper.com

# enable container-based stack -> no, for now we need to workaround https://github.com/travis-ci/travis-ci/issues/6593
sudo: true

install: true
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

script:
  - "mvn --version && mvn clean test verify -B"

after_success:
  # deploy snapshot artifacts to sonatype
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ] && [ "$TRAVIS_TAG" != "" ]; then
        echo "release to maven central";
        mvn versions:set -DnewVersion=$TRAVIS_TAG -DgenerateBackupPoms=false;
        mvn deploy -P release --settings mvn-settings.xml -DskipTests=true -B;
    elif [ "$TRAVIS_JDK_VERSION" == "openjdk8" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        mvn deploy --settings mvn-settings.xml -DskipTests=true -B;
    else
        echo "Not deploying artifacts for $TRAVIS_BRANCH";
    fi

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: "mvn versions:set -DnewVersion=$TRAVIS_TAG -DgenerateBackupPoms=false && mvn --settings .travis.settings.xml jib:build -B"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    jdk: openjdk11

env:
  global:
    secure: v2gGJWEd4PxADr6cDiM7mbZMcqaOFLku9nwXGPRSPBMDuwhxr221PNqBZ7j9WlvSF6seZGXt/KecQHPGf5R/Sa+OWwQ8atqPujUvQAO464VVAxn8ZqyTICyQ/t2R+WJTyWzOXnzfIHqBzQMmF+f/9aXMOz8P6ZHOtSDTWMYugDENGCShs2rvGg/v3YW5lbTR1rOKCNnzB5wcrpdiZLIlF9/weaN/5t+ZJ2Fw50UnG3bpNRX3Uy8zcWeB7ItSeNIpOEfFlRFeUaBhq5iOVBUGK5glqsrdxwvKjlBwRKCuFBJva+xuWuwVJu8uuA4Y4nlArJBQOtfHZSnim5ZOZlj3Q8A/i+fra2dX/OLoOPBdYDsll4/VUISkceYicOvwpTvkQSFjOH99QtL2bbSCXQQ5IzFQK0qSkGwFYzBJPdDFrgkMFSmt1zAyiZRpNBlL6fN5+ndkBCusPtH/1vtuJKsmJ0AsifCz4sczF/dCmPeUUPba2KHG+z+fV8l9+Di6j10KBMx+XDaU5RWdSbP5OTID2TKpMulf6J+ikRxmSX7r1hDO9+P4XlFDOxVw48iuWkvU/5zNT/UbWrcLGF+y0IRe+GTLZU8eGdQjSg8o0zpLIfKbf1sYh9R0cFBcaLiYFyO3BMP+LD1CP3nkCUF05IQszwBMjOY2Kxx/mX9d+RlN4YA=
